apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-backend-deployment 
  labels:
    app: rabbitmq-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-backend
  template:
    metadata:
      labels:
        app: rabbitmq-backend
    spec:
      containers:
      - name: rabbitmq-backend
        image: chaphe/backend-shipping-image:1.0
        ports:
        - containerPort: 3000
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-backend-service 
spec:
  type: NodePort
  selector:
    app: reviews-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30900
